default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
#  socket: /var/mysql/mysqld.sock

development:
  <<: *default
  database: SE04_Nhom4_1_development

test:
  <<: *default
  database: SE04_Nhom4_1_test

production:
  <<: *default
  database: SE04_Nhom4_1_production
  username: SE04_Nhom4_1
  password: <%= ENV["SE04_NHOM4_1_DATABASE_PASSWORD"] %>
